services:
  localstack: 
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack:latest
    environment: 
      - ENVIRONMENT=local
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=000000000000
      - AWS_SECRET_ACCESS_KEY=000000000000
      - PYDEVD_DISABLE_FILE_VALIDATION=${PYDEVD_DISABLE_FILE_VALIDATION:-1}
      - DEBUG=${DEBUG:-0}
      - LAMBDA_DEBUG_MODE=${LAMBDA_DEBUG_MODE:-0}
      - LAMBDA_DOCKER_FLAGS=-p 19891:19891
      # - EDGE_PORT=4566 # deprecated, use GATEWAY_LISTEN
      - GATEWAY_LISTEN=0.0.0.0:4566
      - SERVICES=s3,lambda,logs
    ports: 
      - "0.0.0.0:4566:4566"            # LocalStack Gateway
      - "0.0.0.0:4510-4559:4510-4559"  # external services port range
    volumes:
      - ./localstack/json-converter.zip:/var/lib/localstack/lambda/json-converter.zip
      - /var/run/docker.sock:/var/run/docker.sock  # for localstack to run docker
      - ./localstack/scripts/setup.sh:/etc/localstack/init/ready.d/setup.sh # ready hook
      - ./localstack/s3-notif-config.json:/var/lib/localstack/s3-notif-config.json
    networks:
        - local-development
  
networks:
  local-development:
    driver: bridge