services:
  localstack: 
    image: localstack/localstack:latest
    environment: 
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=000000000000
      - AWS_SECRET_ACCESS_KEY=000000000000
      # - EDGE_PORT=4566 # deprecated, use GATEWAY_LISTEN
      - GATEWAY_LISTEN=0.0.0.0:4566
      - SERVICES=s3,lambda,logs
    ports: 
      - '4566-4583:4566-4583'
    volumes:
      - ./localstack/lambda:/var/lib/localstack/lambda
      - /var/run/docker.sock:/var/run/docker.sock  # for localstack to run docker
      - ./localstack/scripts/setup.sh:/etc/localstack/init/ready.d/setup.sh # ready hook
      - ./localstack/s3-notif-config.json:/var/lib/localstack/s3-notif-config.json